inherit_from: .rubocop_todo.yml

require:
  - rubocop-i18n
  - rubocop-performance

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'ext/**/*.rb'
  Exclude:
    - '**/*.erb'
    - 'acceptance/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'ext/suse/puppet.spec'
    - 'lib/puppet/vendor/**/*'
    - 'lib/puppet/pops/parser/eparser.rb'

Metrics:
  Enabled: false

#################### Layout ###########################

Layout/AlignArguments:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false
