inherit_from: .rubocop_todo.yml

require:
  rubocop-i18n

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib/**/*.rb'
    - 'ext/**/*.rb'
  Exclude:
    - '**/*.erb'
    - 'acceptance/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'ext/suse/puppet.spec'
    - 'lib/puppet/vendor/**/*'
    - 'lib/puppet/pops/parser/eparser.rb'

# puppet uses symbol booleans in types and providers to work around long standing
# bugs when trying to manage falsey pararameters and properties
Lint/BooleanSymbol:
  Enabled: true
  Exclude:
    - 'lib/puppet/type.rb'
    - 'lib/puppet/type/**/*.rb'
    - 'lib/puppet/provider/**/*.rb'
    - 'lib/puppet/reference/providers.rb'
    - 'lib/puppet/parameter/value.rb'

# This breaks the ruby convention of passing &block and using block_given?
Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
