inherit_from: .rubocop_todo.yml

require:
  rubocop-i18n

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib/**/*.rb'
    - 'ext/**/*.rb'
  Exclude:
    - '**/*.erb'
    - 'acceptance/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'lib/puppet/external/**/*'
    - 'lib/puppet/vendor/**/*'
    - 'lib/puppet/pops/model/ast.rb'
    - 'lib/puppet/pops/parser/eparser.rb'
